/**
 * WRC Fantasy Football — 2026 NFL Player Pool
 * ~250 draftable players with ADP rankings for the 2026 season
 * Positions: QB, RB, WR, TE, K, DST
 */

export interface NFLPlayer {
  id: string;
  name: string;
  pos: "QB" | "RB" | "WR" | "TE" | "K" | "DST";
  nflTeam: string;
  adp: number; // average draft position (1 = first overall)
  bye: number | null;
}

let _id = 0;
function p(name: string, pos: NFLPlayer["pos"], nflTeam: string, adp: number, bye: number | null = null): NFLPlayer {
  return { id: `pl${++_id}`, name, pos, nflTeam, adp, bye };
}

export const NFL_PLAYERS_2026: NFLPlayer[] = [
  // ── QBs ────────────────────────────────────────────────────────────────────
  p("Josh Allen",           "QB", "BUF",  1.2, 7),
  p("Lamar Jackson",        "QB", "ATL",  2.1, 11),
  p("Jalen Hurts",          "QB", "PHI",  3.8, 10),
  p("Patrick Mahomes",      "QB", "KC",   5.2, 5),
  p("Joe Burrow",           "QB", "CIN",  7.4, 6),
  p("C.J. Stroud",          "QB", "HOU",  9.1, 8),
  p("Dak Prescott",         "QB", "DAL",  11.3, 14),
  p("Tua Tagovailoa",       "QB", "ATL",  13.8, 11),
  p("Brock Purdy",          "QB", "SF",   15.2, 8),
  p("Jordan Love",          "QB", "GB",   17.4, 11),
  p("Jayden Daniels",       "QB", "WSH",  19.6, 7),
  p("Sam Darnold",          "QB", "SEA",  22.1, 11),
  p("Anthony Richardson",   "QB", "IND",  25.8, 13),
  p("Drake Maye",           "QB", "NE",   28.3, 11),
  p("Caleb Williams",       "QB", "CHI",  31.7, 10),
  p("Trevor Lawrence",      "QB", "JAC",  34.2, 1),
  p("Kyler Murray",         "QB", "MIN",  37.5, 6),
  p("Geno Smith",           "QB", "NYJ",  42.1, 13),
  p("Kirk Cousins",         "QB", "LV",  46.8, 13),
  p("Derek Carr",           "QB", "NO",   52.3, 8),
  p("Russell Wilson",       "QB", "NYG",  58.9, 8),
  p("Cam Ward",             "QB", "TEN",  64.2, 9),
  p("Bo Nix",               "QB", "DEN",  67.8, 10),
  p("Bryce Young",          "QB", "CAR",  72.4, 5),
  p("Daniel Jones",         "QB", "IND",  88.6, 13),
  p("Jacoby Brissett",      "QB", "ARI",   120.0, 14),
  p("Deshaun Watson",       "QB", "CLE",  125.0, 11),

  // ── RBs ────────────────────────────────────────────────────────────────────
  p("Saquon Barkley",       "RB", "PHI",  4.1, 10),
  p("Jahmyr Gibbs",         "RB", "DET",  6.3, 6),
  p("Derrick Henry",        "RB", "BAL",  8.2, 13),
  p("De'Von Achane",        "RB", "MIA",  10.4, 6),
  p("Jonathan Taylor",      "RB", "IND",  12.6, 13),
  p("Bijan Robinson",       "RB", "ATL",  14.8, 11),
  p("Breece Hall",          "RB", "NYJ",  17.1, 13),
  p("Tony Pollard",         "RB", "TEN",  19.3, 9),
  p("Josh Jacobs",          "RB", "GB",   21.5, 11),
  p("James Cook",           "RB", "BUF",  23.7, 7),
  p("Kyren Williams",       "RB", "LAR",  25.9, 11),
  p("Aaron Jones",          "RB", "MIN",  28.1, 6),
  p("Rhamondre Stevenson",  "RB", "NE",   30.3, 11),
  p("David Montgomery",     "RB", "HOU",  32.5, 8),
  p("Isiah Pacheco",        "RB", "DET",   34.7, 6),
  p("Travis Etienne Jr.",   "RB", "NO",  36.9, 8),
  p("Rachaad White",        "RB", "WSH",  39.1, 7),
  p("Zack Moss",            "RB", "CIN",  41.3, 6),
  p("Najee Harris",         "RB", "LAC",  43.5, 7),
  p("Cam Akers",            "RB", "SEA",  45.7, 11),
  p("Zamir White",          "RB", "LV",   47.9, 13),
  p("Javonte Williams",     "RB", "DAL",  50.1, 14),
  p("Kenneth Walker III",   "RB", "KC",  52.3, 5),
  p("Zach Charbonnet",      "RB", "SEA",  54.5, 11),
  p("D'Andre Swift",        "RB", "CHI",  56.7, 10),
  p("Tyjae Spears",         "RB", "TEN",  58.9, 9),
  p("Raheem Mostert",       "RB", "LV",  61.1, 13),
  p("J.K. Dobbins",         "RB", "DEN",  63.3, 10),
  p("Kareem Hunt",          "RB", "KC",   65.5, 5),
  p("Gus Edwards",          "RB", "LAC",  67.7, 7),
  p("Rico Dowdle",          "RB", "PIT",  69.9, 9),
  p("Ty Chandler",          "RB", "NO",  72.1, 8),
  p("Dameon Pierce",        "RB", "PHI",  74.3, 10),
  p("Ezekiel Elliott",      "RB", "LAC",  76.5, 7),
  p("Roschon Johnson",      "RB", "CHI",  78.7, 10),
  p("Keaton Mitchell",      "RB", "LAC",  80.9, 7),
  p("Quinshon Judkins",     "RB", "CLE",  83.1, 11),
  p("Trey Benson",          "RB", "ARI",  85.3, 14),
  p("MarShawn Lloyd",       "RB", "GB",   87.5, 11),
  p("Blake Corum",          "RB", "LAR",  89.7, 11),
  p("Jaylen Warren",        "RB", "PIT",  91.9, 9),
  p("Braelon Allen",        "RB", "NYJ",  94.1, 13),
  p("Kimani Vidal",         "RB", "LAC",  96.3, 7),

  // ── WRs ────────────────────────────────────────────────────────────────────
  p("CeeDee Lamb",          "WR", "DAL",  3.4, 14),
  p("Tyreek Hill",          "WR", "MIA",  5.8,  6),
  p("Justin Jefferson",     "WR", "CLE",  7.3, 11),
  p("Ja'Marr Chase",        "WR", "CIN",  9.5, 6),
  p("Amon-Ra St. Brown",    "WR", "DET",  11.7, 6),
  p("Puka Nacua",           "WR", "LAR",  13.9, 11),
  p("Davante Adams",        "WR", "LAR",   16.1, 11),
  p("Stefon Diggs",         "WR", "NE",  18.3, 11),
  p("Jaylen Waddle",        "WR", "DEN",  20.5, 10),
  p("Deebo Samuel",         "WR", "SF",   22.7, 8),
  p("DK Metcalf",           "WR", "PIT",  24.9, 9),
  p("Garrett Wilson",       "WR", "NYJ",  27.1, 13),
  p("Chris Olave",          "WR", "NO",   29.3, 8),
  p("Drake London",         "WR", "ATL",  31.5, 11),
  p("Tee Higgins",          "WR", "CIN",  33.7, 6),
  p("Keenan Allen",         "WR", "LAC",  35.9, 7),
  p("Mike Evans",           "WR", "SF",  38.1, 8),
  p("Amari Cooper",         "WR", "LV",  40.3, 13),
  p("Marvin Harrison Jr.",  "WR", "ARI",  42.5, 14),
  p("Rashee Rice",          "WR", "KC",   44.7, 5),
  p("Zay Flowers",          "WR", "BAL",  46.9, 13),
  p("Courtland Sutton",     "WR", "DEN",  49.1, 10),
  p("Diontae Johnson",      "WR", "CLE",  51.3, 11),
  p("Jaxon Smith-Njigba",   "WR", "SEA",  53.5, 11),
  p("Quentin Johnston",     "WR", "LAC",  55.7, 7),
  p("Brandin Cooks",        "WR", "BUF",  57.9, 7),
  p("Michael Pittman Jr.",  "WR", "PIT",  60.1, 9),
  p("Gabe Davis",           "WR", "BUF",  62.3, 7),
  p("Jakobi Meyers",        "WR", "JAC",  64.5, 1),
  p("Darnell Mooney",       "WR", "NYG",  66.7, 8),
  p("Rashid Shaheed",       "WR", "SEA",   68.9, 11),
  p("Odell Beckham Jr.",    "WR", "NYG",  71.1, 8),
  p("Wan'Dale Robinson",    "WR", "TEN",  73.3, 9),
  p("Elijah Moore",         "WR", "PHI",  75.5, 10),
  p("Cedric Tillman",       "WR", "CLE",  77.7, 11),
  p("Tetairoa McMillan",    "WR", "CAR",  79.9, 5),
  p("Brian Thomas Jr.",     "WR", "JAC",  82.1, 1),
  p("Malik Nabers",         "WR", "NYG",  84.3, 8),
  p("Rome Odunze",          "WR", "CHI",  86.5, 10),
  p("Ladd McConkey",        "WR", "LAC",  88.7, 7),
  p("Xavier Legette",       "WR", "CAR",  90.9, 5),
  p("Ricky Pearsall",       "WR", "SF",   93.1, 8),
  p("Keon Coleman",         "WR", "BUF",  95.3, 7),
  p("Adonai Mitchell",      "WR", "NYJ",  97.5, 13),
  p("Troy Franklin",        "WR", "DEN",  99.7, 10),
  p("Marquez Valdes-Scantling", "WR", "DAL", 345.6, 14),
  p("Demario Douglas",      "WR", "NE",   104.1, 11),
  p("Kadarius Toney",       "WR", "CLE",   106.3, 11),
  p("Dontayvion Wicks",     "WR", "PHI",   108.5, 10),
  p("Christian Watson",     "WR", "GB",   110.7, 11),
  p("Rashod Bateman",       "WR", "BAL",  112.9, 13),
  p("Jerry Jeudy",          "WR", "CLE",  115.1, 11),
  p("Josh Downs",           "WR", "IND",  117.3, 13),
  p("Alec Pierce",          "WR", "IND",  119.5, 13),
  p("Tutu Atwell",          "WR", "MIA",  121.7, 6),
  p("Skyy Moore",           "WR", "GB",   123.9, 11),
  p("Khalil Shakir",        "WR", "BUF",  126.1, 7),
  p("Mecole Hardman",       "WR", "KC",   128.3, 5),
  p("Darius Slayton",       "WR", "NYG",  130.5, 8),
  p("Parris Campbell",      "WR", "DAL",  132.7, 14),
  p("Jalen Tolbert",        "WR", "MIA",  134.9, 6),
  p("Tre Tucker",           "WR", "LV",   137.1, 13),
  p("Devin Duvernay",       "WR", "ARI",  139.3, 14),
  p("Tyquan Thornton",      "WR", "KC",   141.5, 5),
  p("Van Jefferson",        "WR", "WSH",  143.7, 7),

  // ── TEs ────────────────────────────────────────────────────────────────────
  p("Travis Kelce",         "TE", "KC",   15.6, 5),
  p("Sam LaPorta",          "TE", "DET",  26.4, 6),
  p("Mark Andrews",         "TE", "BAL",  33.1, 13),
  p("Trey McBride",         "TE", "ARI",  38.8, 14),
  p("Dalton Kincaid",       "TE", "BUF",  44.5, 7),
  p("Evan Engram",          "TE", "DEN",  50.2, 10),
  p("David Njoku",          "TE", "LAC",  55.9, 7),
  p("Kyle Pitts",           "TE", "ATL",  61.6, 11),
  p("Jake Ferguson",        "TE", "DAL",  67.3, 14),
  p("Tucker Kraft",         "TE", "GB",   73.0, 11),
  p("Jonnu Smith",          "TE", "PIT",  78.7, 9),
  p("Chigoziem Okonkwo",    "TE", "WSH",  84.4, 7),
  p("Isaiah Likely",        "TE", "NYG",  90.1, 8),
  p("Juwan Johnson",        "TE", "NO",   95.8, 8),
  p("Tyler Higbee",         "TE", "LAR",  101.5, 11),
  p("Cade Otton",           "TE", "TB",  107.2, 10),
  p("Michael Mayer",        "TE", "LV",   112.9, 13),
  p("Brock Wright",         "TE", "DET",  118.6, 6),
  p("Gerald Everett",       "TE", "CHI",  124.3, 10),
  p("Cole Kmet",            "TE", "CHI",  130.0, 10),
  p("Darren Waller",        "TE", "MIA",  135.7, 6),
  p("Hunter Henry",         "TE", "NE",   141.4, 11),
  p("Austin Hooper",        "TE", "ATL",  147.1, 11),
  p("Noah Fant",            "TE", "NO",  152.8, 8),
  p("Will Dissly",          "TE", "LAC",  158.5, 7),
  p("Taysom Hill",          "TE", "NO",   164.2, 8),

  // ── Ks ─────────────────────────────────────────────────────────────────────
  p("Justin Tucker",        "K",  "BAL",  145.0, 13),
  p("Evan McPherson",       "K",  "CIN",  148.0, 6),
  p("Tyler Bass",           "K",  "BUF",  151.0, 7),
  p("Brandon Aubrey",       "K",  "DAL",  154.0, 14),
  p("Harrison Butker",      "K",  "KC",   157.0, 5),
  p("Jake Elliott",         "K",  "PHI",  160.0, 10),
  p("Cameron Dicker",       "K",  "LAC",  163.0, 7),
  p("Greg Joseph",          "K",  "LV",  166.0, 13),
  p("Jason Myers",          "K",  "SEA",  169.0, 11),
  p("Chase McLaughlin",     "K",  "TB",  172.0, 10),
  p("Cairo Santos",         "K",  "CHI",  175.0, 10),
  p("Matt Gay",             "K",  "LV",  178.0, 13),
  p("Wil Lutz",             "K",  "DEN",  181.0, 10),
  p("Younghoe Koo",         "K",  "NYJ",  184.0, 13),
  p("Nick Folk",            "K",  "ATL",   187.0, 11),
  p("Ryan Succop",          "K",  "TAM",  190.0, 10),
  p("Graham Gano",          "K",  "NYG",  193.0, 8),
  p("Robbie Gould",         "K",  "SF",   196.0, 8),

  // ── DSTs ───────────────────────────────────────────────────────────────────
  p("San Francisco 49ers",  "DST", "SF",  155.0, 8),
  p("Dallas Cowboys",       "DST", "DAL", 999.0, 14),
  p("New England Patriots", "DST", "NE",  161.0, 11),
  p("Pittsburgh Steelers",  "DST", "PIT", 999.0, 9),
  p("Baltimore Ravens",     "DST", "BAL", 999.0, 13),
  p("Buffalo Bills",        "DST", "BUF", 999.0, 7),
  p("Kansas City Chiefs",   "DST", "KC",  173.0, 5),
  p("Miami Dolphins",       "DST", "MIA", 999.0, 6),
  p("Philadelphia Eagles",  "DST", "PHI", 999.0, 10),
  p("Cleveland Browns",     "DST", "CLE", 999.0, 11),
  p("New York Jets",        "DST", "NYJ", 999.0, 13),
  p("Los Angeles Rams",     "DST", "LAR", 999.0, 11),
  p("Indianapolis Colts",   "DST", "IND", 999.0, 13),
  p("Los Angeles Chargers", "DST", "LAC", 999.0, 7),
  p("Denver Broncos",       "DST", "DEN", 999.0, 10),
  p("Green Bay Packers",    "DST", "GB",  200.0, 11),
  p("Minnesota Vikings",    "DST", "MIN", 999.0, 6),
  p("Detroit Lions",        "DST", "DET", 999.0, 6),
  p("Tampa Bay Buccaneers", "DST", "TAM", 999.0, 10),
  p("Seattle Seahawks",     "DST", "SEA", 999.0, 11),
  p("Houston Texans",       "DST", "HOU", 999.0, 8),
  p("Atlanta Falcons",      "DST", "ATL", 999.0, 11),
  p("Jacksonville Jaguars", "DST", "JAC", 999.0, 1),
  p("Carolina Panthers",    "DST", "CAR", 999.0, 5),
  p("Arizona Cardinals",    "DST", "ARZ", 999.0, 14),
  p("Tennessee Titans",     "DST", "TEN", 999.0, 9),
  p("Las Vegas Raiders",    "DST", "LV",  233.0, 13),
  p("New York Giants",      "DST", "NYG", 999.0, 8),
  p("Chicago Bears",        "DST", "CHI", 999.0, 10),
  p("New Orleans Saints",   "DST", "NO",  242.0, 8),
  p("Washington Commanders","DST", "WAS", 999.0, 7),
  p("Cincinnati Bengals",   "DST", "CIN", 999.0, 6),
];

/** Get players not yet drafted (by name) */
export function getAvailablePlayers(draftedNames: Set<string>): NFLPlayer[] {
  return NFL_PLAYERS_2026.filter(p => !draftedNames.has(p.name));
}
