// Auto-generated player→round lookup from 2025 Excel roster
// Owner → player name (lowercase) → draft round (null = FA)
export const PLAYER_DRAFT_ROUNDS: Record<string, Record<string, number | null>> = {
  "Jonas": {
    "jared goff": 7,
    "bryce young": null,
    "jonathan taylor": 5,
    "de'von achane": 6,
    "aaron jones": 8,
    "quinshon judkins": 9,
    "trey benson": 11,
    "justin jefferson": 1,
    "marvin harrison jr.": 2,
    "dk metcalf": 4,
    "jakobi meyers": 10,
    "jerry jeudy": null,
    "darren waller": 18,
    "juwan johnson": null,
    "sam laporta": null,
    "chase mclaughlin": null,
    "cleveland browns": 17,
    "los angeles chargers": null,
  },
  "David R.": {
    "bo nix": 6,
    "jaxson dart": null,
    "alvin kamara": 3,
    "travis etienne": 8,
    "dylan sampson": null,
    "devin singletary": null,
    "jameson williams": 5,
    "chris olave": 8,
    "christian kirk": 14,
    "marquise brown": 17,
    "wan'dale robinson": 18,
    "quentin johnston": null,
    "george kittle": 4,
    "tyler warren": 7,
    "aj barner": null,
    "eddy pineiro": null,
    "joey slye": null,
    "dallas cowboys": null,
  },
  "Jason": {
    "justin herbert": 6,
    "kyler murray": 6,
    "matthew stafford": 17,
    "saquon barkley": 1,
    "omarion hampton": 2,
    "treveyon henderson": 2,
    "kimani vidal": null,
    "terry mclaurin": 2,
    "emeka egbuka": 5,
    "michael pittman": 8,
    "jordan addison": 10,
    "stefon diggs": 12,
    "t.j. hockenson": 6,
    "dalton schultz": null,
    "jake bates": null,
    "joshua karty": null,
    "detroit lions": 13,
    "san francisco 49ers": null,
  },
  "Keith": {
    "jordan love": 9,
    "tyler shough": null,
    "ashton jeanty": 1,
    "jahmyr gibbs": 2,
    "kyle monangai": null,
    "chuba hubbard": null,
    "davante adams": 3,
    "rome odunze": 5,
    "ladd mcconkey": 6,
    "jayden reed": null,
    "chris godwin": null,
    "brock bowers": 4,
    "theo johnson": null,
    "colston loveland": null,
    "brenton strange": null,
    "chris boswell": null,
    "seattle seahawks": 17,
    "new england patriots": null,
  },
  "Dan": {
    "dak prescott": 5,
    "brock purdy": 9,
    "trevor lawrence": 10,
    "derrick henry": 1,
    "tony pollard": 3,
    "christian mccaffrey": 6,
    "brian robinson": 11,
    "justice hill": 16,
    "amon-ra st. brown": 1,
    "a.j. brown": 2,
    "xavier worthy": 4,
    "george pickens": 8,
    "jauan jennings": 11,
    "adonai mitchell": null,
    "mark andrews": 5,
    "hunter henry": 14,
    "tyler loop": null,
    "chicago bears": null,
  },
  "Jamie": {
    "jalen hurts": 2,
    "tua tagovailoa": null,
    "tyrod taylor": null,
    "jaylen warren": 5,
    "chase brown": 7,
    "ollie gordon": 12,
    "dj giddens": 16,
    "ceedee lamb": 1,
    "drake london": 1,
    "jalen coker": 15,
    "troy franklin": null,
    "michael wilson": null,
    "brandon aiyuk": null,
    "travis kelce": 4,
    "cameron dicker": 11,
    "andres borregales": null,
    "denver broncos": 11,
    "jacksonville jaguars": null,
  },
  "Bill": {
    "jayden daniels": 3,
    "drake maye": 8,
    "shedeur sanders": null,
    "jordan mason": 7,
    "cam skattebo": 9,
    "kenneth gainwell": null,
    "tyrone tracy": null,
    "d.j. moore": 4,
    "keenan allen": 15,
    "malik nabers": null,
    "rashid shaheed": null,
    "xavier legette": null,
    "david njoku": 4,
    "zach ertz": 13,
    "cade otton": null,
    "brandon aubrey": 10,
    "will reichard": null,
    "los angeles rams": null,
  },
  "Scott N.": {
    "lamar jackson": 2,
    "daniel jones": null,
    "josh jacobs": 1,
    "isiah pacheco": 3,
    "kyren williams": 5,
    "rhamondre stevenson": 13,
    "tyjae spears": 15,
    "emanuel wilson": null,
    "garrett wilson": 4,
    "nico collins": 6,
    "jaxon smith-njigba": 7,
    "jaylen waddle": 8,
    "andrei iosivas": null,
    "kyle pitts": 12,
    "oronde gadsden": null,
    "evan mcpherson": null,
    "kansas city chiefs": null,
    "houston texans": null,
  },
  "Shawn": {
    "baker mayfield": 6,
    "jacoby brissett": null,
    "d'andre swift": 4,
    "javonte williams": 8,
    "woody marks": null,
    "chris rodriguez jr.": null,
    "devin neal": null,
    "jacory croskey-merritt": null,
    "courtland sutton": 3,
    "ricky pearsall": 5,
    "khalil shakir": 12,
    "alec pierce": null,
    "mike evans": null,
    "trey mcbride": 7,
    "harold fannin": 16,
    "ka'imi fairbairn": null,
    "green bay packers": 15,
    "tampa bay buccaneers": null,
  },
  "David S.": {
    "josh allen": 1,
    "patrick mahomes": 4,
    "breece hall": 3,
    "rj harvey": 3,
    "david montgomery": 7,
    "bucky irving": 8,
    "rachaad white": 16,
    "kareem hunt": null,
    "ja'marr chase": 1,
    "rashee rice": 5,
    "puka nacua": 6,
    "romeo doubs": 15,
    "dalton kincaid": 8,
    "jake ferguson": 12,
    "isaiah likely": null,
    "cam little": null,
    "carolina panthers": null,
    "new york giants": null,
  },
  "Greg": {
    "c.j. stroud": 9,
    "joe burrow": null,
    "cam ward": null,
    "kenneth walker iii": 2,
    "zach charbonnet": 9,
    "j.k. dobbins": 9,
    "rico dowdle": 14,
    "tetairoa mcmillan": 3,
    "zay flowers": 4,
    "brian thomas jr.": 7,
    "brandin cooks": 18,
    "tucker kraft": 7,
    "jonnu smith": 12,
    "chigoziem okonkwo": 14,
    "jake elliott": 13,
    "cairo santos": null,
    "philadelphia eagles": 10,
  },
  "Scott M.": {
    "caleb williams": 9,
    "sam darnold": 15,
    "bijan robinson": 1,
    "james cook": 3,
    "tyler allgeier": 12,
    "ray davis": 13,
    "blake corum": 18,
    "zonovan knight": null,
    "tee higgins": 1,
    "devonta smith": 5,
    "kayshon boutte": null,
    "parker washington": null,
    "christian watson": null,
    "evan engram": 7,
    "dallas goedert": 16,
    "jason myers": null,
    "pittsburgh steelers": 10,
    "buffalo bills": null,
  },
};
